In [29]:
import pandas as pd

df = pd.read_csv('facebook_results_new.csv')


df

                                                 text
0    Hanya replika bonsai daur ulang plastik kresek 🙏
1   Kembali, Ketua Umum Adupi Christine Halim diwa...
2   Hari jum'at kemarin tgl 26, hari terahir sy ju...
3         hanya Replika ( daur ulang sampah plastik )
4   Beberapa simbol daur ulang yang perlu kita ket...
..                                                ...
77  Moorlife itu bukan untuk pajangan ya bun\nBuka...
78  🌏 Plastik Bukan Trend Lagi, Saatnya Pilih Kema...
79  Sampah sedotan plastik sebanyak ini kami kumpu...
80  🌍♻️ *Mengubah Sampah Menjadi Berkah: Daur Ulan...
81  WPC atau wood plastic composite tampak seperti...

[82 rows x 1 columns]

In [ ]:

auth_token = 'sample_auth_token'
filename = 'results.csv'
search_keyword = 'daur ulang plastik lang:id'
limit = 1000

!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token {auth_token}

In [33]:
#Install nodejs
#!node -v
#Rupanya udah install

auth_token = '040842c16d1037b25e7e0c77da261a63dc323a95'
filename = 'results.csv'
search_keyword = 'daur ulang plastik sedikit lang:id'
#Keywords: daur ulang plastik, #daurulang, daur ulang sampah plastik, #daurulangplastik, olah sampah plastik,daur ulang plastik, sampah plastik Indonesia, daur ulang pet, olah plastik pet all with lang:id
#More keywords: daur ulang plastik jelek, daur ulang plastik kurang, daur ulang plastik masih,daur ulang plastk belum, daur ulang plastik rendah, daur ulang plastik jarang, daur ulang plastik telat, daur ulang plastik tidak
#even more keywords: daur ulang plastik hanya, daur ulang plastik sedikit
limit= 500
!npx --yes tweet-harvest@latest -o "{filename}" -s "{search_keyword}" -l {limit} --token {auth_token}

Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/results.csv, renaming to ./tweets-data/results.old.csv

Filling in keywords: daur ulang plastik sedikit lang:id


-- Scrolling... (1)

Your tweets saved to: c:\Users\hp\Desktop\python coba\tweets-data\results.csv
Total tweets saved: 20

-- Scrolling... (1) (2)

Your tweets saved to: c:\Users\hp\Desktop\python coba\tweets-data\results.csv
Total tweets saved: 40

-- Scrolling... (1)

Your tweets saved to: c:\Users\hp\Desktop\python coba\tweets-data\results.csv
Total tweets saved: 60

-- Scrolling... (1)

Your tweets saved to: c:\Users\hp\Desktop\python coba\tweets-data\results.csv
Total tweets saved: 75

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1)
-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)
-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1)
-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 75 tweets, done scrolling...

[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result
[v2.6.1] No more tweets found, please check your search criteria and csv file result

In [1]:
import re

def remove_links(text):
    return re.sub(r'http\S+|www\S+|https\S+', '', text)

In [2]:
#Clean the results and pass the unique data to results.csv
import pandas as pd
import os
file_path = 'new_result.csv'
df = pd.read_csv('tweets-data/results.csv')

relevant_columns = ['full_text', 'created_at']
df = df[relevant_columns]
df['full_text'] = df['full_text'].apply(remove_links)
df = df.dropna()
df =df.rename(columns={
    'full_text': 'tweet',
    'created_at': 'date_created',  
})


df.to_csv(file_path,index=False, header=True)
    


#df_res = pd.read_csv('results.csv')

In [ ]:
old_data = pd.read_csv('twitter_results.csv')


old_data = old_data.drop_duplicates()
old_data = old_data['tweet'].apply(remove_links)
old_data

0      Soal Timor Leste daur ulang seluruh sampah pla...
1      Kemarin: peluncuran produk kolaborasi @jenahar...
2      Halo Sahabat yuk tonton video berikut ini untu...
3      APA ITU 3D PRINTING HOUSE? 3D printing house a...
4      2025 saatnya sutainable kalcer. Pakai produk y...
                             ...
944    @Priciezye @bankmandiri ternyata hanya dengan ...
945    Dan kenapa alumunium? Karena kita mesti diurut...
946    @cimotyy luar biasa sekali! BSI memang tidak h...
947    @hujanrintik___ @icannn___ Bukan hanya pakar t...
948    Sampah plastik bukan hanya masalah lingkungan ...
Name: tweet, Length: 949, dtype: object

In [ ]:
df = pd.read_csv('new_result.csv')

old_data = pd.read_csv('twitter_results.csv')
df.drop_duplicates(subset=['tweet'], inplace=True)
df = df[~df['tweet'].isin(old_data)]
old_data = pd.concat([old_data, df['tweet']], ignore_index=True)
old_data = old_data.drop_duplicates()
old_data.to_csv('twitter_results.csv',header=True)
df.to_csv('new_result.csv',header=True)

In [42]:

relevant_columns = ['full_text', 'created_at']
df = df[relevant_columns]
df['full_text'] = df['full_text'].apply(remove_links)
df = df.dropna()
df =df.rename(columns={
    'full_text': 'tweet',
    'created_at': 'date_created',  
})

df

                  tweet         date_created
0   Proses daur ulan...  Tue Feb 05 14:02...
1      harus dibersi...  Sun Mar 26 09:46...
2   yuk guys kurangi...  Wed Jul 05 02:38...
3   sedikit sentuhan...  Wed Aug 30 05:45...
4   @pinotski Punya ...  Fri Nov 23 03:49...
..                  ...                  ...
70  @nanaaabcd iyaa ...  Fri Feb 05 11:26...
71  @waste4change @C...  Thu Dec 22 14:33...
72  Kami menyadari s...  Thu Feb 21 06:46...
73  daur ulang sampa...  Fri Aug 11 08:44...
74  @detikcom @detik...  Tue Mar 05 01:30...

[75 rows x 2 columns]

In [2]:
!taskkill /IM node.exe /F

SUCCESS: The process "node.exe" with PID 15840 has been terminated.
SUCCESS: The process "node.exe" with PID 25208 has been terminated.

In [ ]:
import requests
import time

def FacebookAPICall(search, limit):
    url = "https://facebook-scraper3.p.rapidapi.com/search/posts"
    headers = {
        "x-rapidapi-key": "564af8b867mshb69c83d38872dfep10ddddjsn3981c2299832",
        "x-rapidapi-host": "facebook-scraper3.p.rapidapi.com"
    }
    cursor = None 
    all_posts = []
    while len(all_posts) < limit:
        params = {"query": search}
        if cursor:
            params["cursor"] = cursor
        response = requests.get(url, headers=headers, params=params)
        if response.status_code != 200:
            print("Error:", response.status_code, response.text)
            break
        data = response.json()
        posts = data.get("results", [])
        all_posts.extend(posts)
        print(f"Fetched {len(posts)} posts (Total: {len(all_posts)})")
        cursor = data.get("cursor")
        if not cursor:
            print("No more pages.")
            break
        time.sleep(1)
    print(f"Total collected posts: {len(all_posts)}")
    return all_posts

In [ ]:
facebook_temp_data = FacebookAPICall("daur ulang plastik hanya", 200)
#Queries: daur ulang limbah plastik, daur ulang sampah plastik, pengolahan sampah plastik, daur ulang plastik
#daur ulang plastik masih,daur ulang plastk belum, daur ulang plastik rendah,bukan
print(facebook_temp_data)

Fetched 3 posts (Total: 3)
Fetched 2 posts (Total: 5)
Fetched 3 posts (Total: 8)
Fetched 3 posts (Total: 11)
Fetched 3 posts (Total: 14)
Fetched 3 posts (Total: 17)
Fetched 3 posts (Total: 20)
Fetched 3 posts (Total: 23)
Fetched 3 posts (Total: 26)
Fetched 3 posts (Total: 29)
Fetched 3 posts (Total: 32)
Fetched 2 posts (Total: 34)
Fetched 3 posts (Total: 37)
Fetched 3 posts (Total: 40)
Fetched 3 posts (Total: 43)
Fetched 3 posts (Total: 46)
Fetched 3 posts (Total: 49)
Fetched 3 posts (Total: 52)
Fetched 3 posts (Total: 55)
Fetched 3 posts (Total: 58)
Fetched 3 posts (Total: 61)
Fetched 3 posts (Total: 64)
Fetched 3 posts (Total: 67)
Fetched 3 posts (Total: 70)
Fetched 3 posts (Total: 73)
Fetched 3 posts (Total: 76)
Fetched 3 posts (Total: 79)
Fetched 3 posts (Total: 82)
Fetched 3 posts (Total: 85)
Fetched 3 posts (Total: 88)
Fetched 3 posts (Total: 91)
Fetched 3 posts (Total: 94)
Fetched 3 posts (Total: 97)
Fetched 3 posts (Total: 100)
Fetched 3 posts (Total: 103)
Fetched 3 posts (Total: 106)
Fetched 3 posts (Total: 109)
Fetched 3 posts (Total: 112)
Fetched 3 posts (Total: 115)
Fetched 0 posts (Total: 115)
No more pages.
Total collected posts: 115

In [58]:
for post in facebook_temp_data:
   print(post['message'])
   print(post['timestamp'])

Hanya replika bonsai daur ulang plastik kresek 🙏
1629153065
Kembali, Ketua Umum Adupi Christine Halim diwawancarai oleh Metro TV hari ini untuk  acara The Nation terkait daur ulang plastik.

Dalam wawancara tersebut Christine Halim menyatakan, plastik hanya butuh beberapa detik untuk didaur ulang menjadi barang-barang yang bermanfaat. Jadi tidak butuh waktu sampai 500 atau ribuan tahun untuk terurai.

Di pabrik daur ulangnya, sampah botol plastik didaur ulang menjadi dakron, geotextile (pelapis untuk infrastructure jalan tol) Dan strapping band. Plastik kalau dikelola dengan baik bisa bernilai ekonomi dan tidak menjadi sampah yang mengotori lingkungan.

#wastemanagement
#circulareconomy
#indonesiabersih
1594702161
Hari jum'at kemarin tgl 26, hari terahir sy jual semua jenis gilingan plastik  ke pelanggan sy, yg sdh berjalan sekitar 2 thn.

Sekarang sy akan mencari bos baru yg asik, yg bisa di ajak kerja sm dengan baik, tdk hanya memikirkan keuntungan dirinya sendiri.

Barang yg sy giling barang pungutan, bukan bs pabrik.

Yg sy giling jenis pp kambangan
Dalam 1 minggu kurang lebih 7ton,
Setok sekarang sedang kosong
Lokasi tangerang banten.
1593274765
hanya Replika ( daur ulang sampah plastik )
1747394219
Beberapa simbol daur ulang yang perlu kita ketahui:

1.      PETE (1)

Jenis plastik ini hanya bisa digunakan sekali pakai. Tidak disarankan untuk menggunakan berulang kali, terutama mengisinya dengan air hangat karena lapisan polimer dan zat karsinogenik pada plastik dapat larut (lepas) dan menyebabkan kanker pada organ tubuh manusia.

2.      HDPE (2)

Simbol ini digunakan untuk sebuah plastic yang terbuat dari high desity polyethylene yang biasanya digunakan untuk gallon air minum, botol shampo, dan plastik kemasan tebal lainnya. Jenis plastik ini termasuk golongan plastik yang cukup aman digunakan berulang kali karena paling sering didaur ulang dengan nilai ekonomi dan proses daur ulang yand sederhana.

3.      PVC (3)

Barang-barang plastik yang terbuat dari plastik polyvinyl chloride ini sering juga disebut dengan “plastik beracun” karena mengandung berbagai macam bahan kimia beracun yang dapat larut dan berbahaya bagi kesehatan. Sehingga perlu dihindari menggunakan jenis plastik ini untuk kemasan makanan dan minuman.

4.      LDPE (4)

Jenis plastik ini terbuat dari bahan low density polyethylene yang bersifat elastis, memiliki daya tahan yang lama dan dapat digunakan untuk berulang kali. Biasanya terdapat pada kantong plastik (kresek), kantong plastik sampah, tas belanja, hingga bungkus makanan.

5.      PP (5)

Simbol ini digunakan untuk plastik yang terbuat dari polypropylene. Barang plastik dengan simbol ini baik digunakan sebagai tempat makanan maupun minuman karena terbuat dari polypropylene yang sangat kuat dan cukup aman digunakan meski pada suhu yang panas.

6.      PS (6)

Plastik jenis ini terbuat dari polystyrene yang banyak digunakan sebagai tempat makan syrofoam, tempat telur, sendok/garpu plastik, foam packaging hingga bahan bangunan (bahan flooring). Plastik ini dapat mengeluarkan styrene yang merupakan zat karsinogen yang dapat menyebabkan kanker.

7.      Other (7)

Penggunaan jenis plastik ini untuk makanan atau minuman sangat berbahaya karena bisa menghasilkan racun Bisphenol-A (BPA)
1685368223
hanya Replika ( daur ulang sampah plastik )
1747394219
Daur Ulang Kreatif: Cara Memanfaatkan Botol Bekas Menjadi Barang Bernilai Guna

Botol plastik bekas sering kali menjadi limbah yang mencemari lingkungan. Padahal, dengan sedikit kreativitas, botol bekas bisa diubah menjadi barang yang lebih bermanfaat, seperti pot tanaman, tempat penyimpanan, atau bahkan kerajinan dekoratif. Artikel ini akan membahas cara-cara memanfaatkan botol bekas dengan mudah serta langkah-langkah pembuatannya.

Tahapan Memanfaatkan Botol Bekas

1. Menentukan Ide Pemanfaatan

Sebelum mulai, tentukan fungsi baru dari botol bekas. Beberapa ide kreatif meliputi:

Pot tanaman vertikal

Tempat penyimpanan alat tulis

Wadah sabun cair

Lampu hias dari botol plastik

2. Mengumpulkan Alat dan Bahan

Persiapkan botol bekas yang akan digunakan serta alat pendukung seperti:

Gunting atau cutter

Lem tembak

Cat atau spidol untuk dekorasi

Tali, kain, atau bahan tambahan lainnya

3. Membersihkan dan Menyiapkan Botol

Cuci botol dengan sabun untuk menghilangkan sisa isi dan bau. Keringkan sebelum digunakan agar lebih mudah diolah.

4. Memotong dan Membentuk Sesuai Kebutuhan

Gunakan gunting atau cutter untuk memotong botol sesuai desain yang diinginkan. Hati-hati saat memotong agar hasilnya rapi dan tidak melukai tangan.

5. Menghias dan Menyempurnakan Bentuk

Tambahkan warna, gambar, atau elemen dekoratif agar hasilnya lebih menarik. Jika digunakan sebagai pot tanaman, buat lubang kecil di bagian bawah untuk drainase air.

6. Menggunakan dan Merawat Hasil Daur Ulang

Setelah selesai, gunakan hasil kreasi sesuai fungsinya. Jika membuat pot tanaman, pastikan tanaman mendapatkan perawatan yang baik agar tumbuh subur.

Dengan kreativitas, botol bekas tidak hanya menjadi sampah tetapi bisa berubah menjadi barang yang bermanfaat dan estetis. Selain membantu mengurangi limbah plastik, ini juga bisa menjadi peluang usaha bagi yang ingin mencoba bisnis daur ulang.
#CARA
#tips
#ideas
1738194642
Assalamu'alaikum. Siapa tau disini ada yang mau usaha daur ulang limbah plastik, saya tau konsep, jenis barang, marketnya, barang ada yg mau buka saya kasih konsepnya/ilmunya dari pengalaman saya. Terimakasih. Maaf hanya sekedar berbagi aja semoga bermanfaat untuk yg  mau usaha di limbah plastik.
1727012513
Assalamu'alaikum. Siapa tau disini ada yang mau usaha daur ulang limbah plastik, saya tau konsep, jenis barang, marketnya, barang ada yg mau buka saya kasih konsepnya/ilmunya dari pengalaman saya. Terimakasih. Maaf hanya sekedar berbagi aja semoga bermanfaat untuk yg  mau usaha di limbah plastik.
1727012513
Daur ulang sampah plastik di rumah tidak hanya membantu mengurangi limbah plastik yang merusak lingkungan, tetapi juga memberikan kesempatan untuk berkreasi dan membuat barang-barang berguna.
1720751613
Alat daur ulang yang bisa menginspirasi kita untuk diarahkan memanfaatkan barang-barang yang tidak terpakai lagi, khususnya botol plastik. Silahkan simak video ini.

NB: hanya video cara kerja bukan bagaimana cara membuat alat 🙏🙏
1714727387
Kerjasama dibidang penggilingan daur ulang plastik
Jenis plastik yang digiling jenis pp ,seperti gelas plastik ,ember dan bahan plastik lain nya
Profit keuntungan 10-20% perminggu
Kenapa mesti gabung dibisnis ini .??
Ya karna bahan baku melimpah
Dan daya jual dan permintaaan yang tinggi
Dan minim resiko nya

Disini saya ingin menawarkan kerjasama kebapak /ibu yang bersedia mau menanamkan modal nya
Modal yang saya butuhkan 5-10jta (hanya untuk pengembangkan usaha dan bahan baku )

Untuk daerah cikarang dan sekitar nya bisa ,cek lokasi usaha nya bisa survei langsung bagaimana proses nya

Untuk lebih lanjut bisa langsung hub :
089529738609
1746863712
*BARU !!!*

_*Oriflame Shower Puff*_

*Hanya Rp.21.900,- saja 😍*

Setelah sekian lama tidak produksi, kali ini Oriflame mengeluarkan lagi shower puffnya 🥳.
Shower puff ini terbuat dari 100% polyester daur ulang dan 100% kemasan plastik daur ulang juga, karena Oriflame menjaga komitmen untuk menjaga kelestarian alam sebaik mungkin.
Walaupun bahan daur ulang, tp kwalitas shower puffnya bagus banget lho. Dipakai bertahun-tahun juga aweeeett....
Dengan harga yg super terjangkau dan kwalitas yg supeer bagus, shower puff ini menjadi produk yg "worth it" banget kamu beli.

Uk 12x10,5 cm
Kode 47543

Harga normal Rp.31.900,-
1738553399
Hari jum'at kemarin tgl 26, hari terahir sy jual semua jenis gilingan plastik  ke pelanggan sy, yg sdh berjalan sekitar 2 thn.

Sekarang sy akan mencari bos baru yg asik, yg bisa di ajak kerja sm dengan baik, tdk hanya memikirkan keuntungan dirinya sendiri.

Barang yg sy giling barang pungutan, bukan bs pabrik.

Yg sy giling jenis pp kambangan
Dalam 1 minggu kurang lebih 7ton,hd tutup botol mambo dalam 1 minggu ada 3 ton, ld, hd blowing.
Setok sekarang sedang kosong
Lokasi tangerang banten.
1593275413
Hari jum'at kemarin tgl 26, hari terahir sy jual semua jenis gilingan plastik  ke pelanggan sy, yg sdh berjalan sekitar 2 thn.

Sekarang sy akan mencari bos baru yg asik, yg bisa di ajak kerja sm dengan baik, tdk hanya memikirkan keuntungan dirinya sendiri.

Barang yg sy giling barang pungutan, bukan bs pabrik.

Yg sy giling jenis pp kambangan
Dalam 1 minggu kurang lebih 7ton,hd tutup botol mambo dalam 1 minggu ada 3 ton, ld, hd blowing.
Setok sekarang sedang kosong
Lokasi tangerang banten.
1593275413
None
1740286030
Sampah yang hanya dipandang sebelah mata tetapi kalau bisa cara memanfaatkan nya bisa menjadi Nilai Ekonomi, tidak bisa dimanfaat kan sebagi daur Ulang kerajinan , bisa Dijual dengan pengempul sampah (kang rongsokan) dampak positif nya Lingkungan menjadi bersih bebas sampah Plastik..
.
.
Tanpa disadari sampah yg berserak kalau dijual uangnya bisa buat tambah2 beli jajan anak 😍😍

Semoga menjadi Motivasi untuk lebih peduli dengan Lingkungan 🙏
1740565520
Di butuhkan sampah plastik multilayer/campuran (PP/PE/ALUMUNIUM) dan (PE/KERTAS/ALUMUNIUM)

contohnya

bungkus snack chiki , cheetoz, taro, dll
saset sekali pakai pantene, lifeboy,dll
kotak teh botol, kotak susu indomilk, tempat makan KFC dll

Tolong info sehari bisa supply berapa KG/TON dan hanya terima multilayer/campuran.
1654584076
*BARU !!!*

_*Oriflame Shower Puff*_

*Hanya Rp.21.900,- saja 😍*

Setelah sekian lama tidak produksi, kali ini Oriflame mengeluarkan lagi shower puffnya 🥳.
Shower puff ini terbuat dari 100% polyester daur ulang dan 100% kemasan plastik daur ulang juga, karena Oriflame menjaga komitmen untuk menjaga kelestarian alam sebaik mungkin.
Walaupun bahan daur ulang, tp kwalitas shower puffnya bagus banget lho. Dipakai bertahun-tahun juga aweeeett....
Dengan harga yg super terjangkau dan kwalitas yg supeer bagus, shower puff ini menjadi produk yg "worth it" banget kamu beli.

Uk 12x10,5 cm
Kode 47543

Harga normal Rp.31.900,-
1738553399
None
1740286030
DAUR ULANG KANTONG PLASTIK KRESEK, daur ulang botol plastik

Mesin daur ulang kantong plastik kresek dan botol plastik adalah teknologi yang dirancang untuk mengolah sampah plastik menjadi bahan baku yang dapat digunakan kembali. Mesin ini bekerja dengan cara menghancurkan, mencuci, dan mencairkan plastik yang sudah tidak terpakai, baik itu kantong plastik kresek maupun botol plastik, menjadi pellet atau material plastik yang siap digunakan dalam proses produksi. Proses daur ulang ini tidak hanya mengurangi jumlah sampah plastik yang mencemari lingkungan, tetapi juga mengurangi kebutuhan akan bahan baku plastik baru, yang berdampak positif terhadap penghematan sumber daya alam.

Keunggulan mesin daur ulang plastik ini terletak pada kemampuannya untuk mengolah berbagai jenis plastik dengan efisiensi tinggi, mengubahnya menjadi produk yang bermanfaat kembali. Mesin ini sering digunakan di industri daur ulang untuk mendukung kelestarian lingkungan, mengurangi polusi plastik, serta menghasilkan bahan baku yang dapat dimanfaatkan oleh berbagai sektor industri, mulai dari pembuatan produk plastik baru hingga barang-barang komposit lainnya. Dengan teknologi yang semakin berkembang, mesin ini juga dapat dilengkapi dengan sistem pemisahan otomatis untuk memproses berbagai jenis plastik secara terpisah, sehingga meningkatkan kualitas hasil daur ulang.

#DaurUlangPlastik
#RecyclingPlastic
#KantongPlastikKresek
#DaurUlangBotolPlastik
#LingkunganBersih
#PlastikDaurUlang
#InovasiDaurUlang
#HematSumberDaya
#JagaBumi
#EcoFriendly
1740382772
**Dapatkan Plastik Polymailer Kharisma Ukuran 17 x 30 Hanya di Toko Kami!**

Temukan keunggulan dan kualitas plastik polymailer Kharisma ukuran 17 x 30 yang hanya tersedia di toko kami. Dengan desain yang tahan lama dan kekuatan ekstra, polymailer ini ideal untuk mengirimkan barang-barang Anda dengan aman dan profesional. Ukuran 17 x 30 cm memberikan ruang yang cukup untuk berbagai jenis paket, sekaligus memudahkan proses pengemasan.

Jangan lewatkan kesempatan untuk memperoleh produk eksklusif ini hanya di toko kami. Pilihlah plastik polymailer Kharisma untuk solusi pengemasan yang efisien dan berkualitas! Hubungi kami untuk pemesanan dan informasi lebih lanjut.

https://s.shopee.co.id/8pT2X4Nh3q
1726467661
KODE DAUR ULANG

Sering kita temukan kode2 angka dengan 3 panah melingkar pada sebuah kemasan, tidak hanya plastik, tapi juga pada kemasan kertas, kaca, dan logam.

Simbol ini dirancang pada tahun 1970 oleh Gary Anderson, seorang mahasiswa di University of Southern California. Desainnya merupakan bagian dari kontes nasional yang disponsori oleh Container Corporation of America (CCA) sebagai tanggapan terhadap Hari Bumi Sedunia. Karena konsumen menjadi lebih sadar lingkungan, CCA ingin mengembangkan label untuk produk daur ulang dan dapat didaur ulang serta meningkatkan kesadaran tentang daur ulang.

Nomor daur ulang adalah sistem untuk mengidentifikasi berbagai jenis plastik dan menentukan apakah plastik tersebut dapat didaur ulang atau tidak. Simbol daur ulang plastik yang memuat nomor tersebut biasanya terdapat di bagian bawah wadah plastik, di dalam segitiga yang terdiri dari tiga anak panah yang saling berkejaran. Simbol anak panah yang berkejaran ini telah menjadi sinonim untuk mengidentifikasi barang yang dapat didaur ulang. Namun, hanya karena terdapat simbol daur ulang pada kemasan Anda, bukan berarti kemasan tersebut dapat dengan mudah didaur ulang.

Kemasan multi-material tidak dapat didaur ulang kecuali materialnya dipisahkan. Misalnya, pompa plastik dengan pegas logam tidak dapat didaur ulang kecuali pegasnya dipisahkan dari bagian pompa lainnya. Inovasi kemasan terkini , seperti produk mono-material seperti pompa serba plastik, memudahkan daur ulang produk ini.
1735539133
**Dapatkan Plastik Polymailer Kharisma Ukuran 17 x 30 Hanya di Toko Kami!**

Temukan keunggulan dan kualitas plastik polymailer Kharisma ukuran 17 x 30 yang hanya tersedia di toko kami. Dengan desain yang tahan lama dan kekuatan ekstra, polymailer ini ideal untuk mengirimkan barang-barang Anda dengan aman dan profesional. Ukuran 17 x 30 cm memberikan ruang yang cukup untuk berbagai jenis paket, sekaligus memudahkan proses pengemasan.

Jangan lewatkan kesempatan untuk memperoleh produk eksklusif ini hanya di toko kami. Pilihlah plastik polymailer Kharisma untuk solusi pengemasan yang efisien dan berkualitas! Hubungi kami untuk pemesanan dan informasi lebih lanjut.

https://s.shopee.co.id/8pT2X4Nh3q
1726467661
Kostum Karnaval berupa gaun daur ulang. Terbuat dari koran, plastik. Walaupun hanya terbuat dari bahan daur ulang tetapi tidak mengurangi kecantikan orang yang memakai nya. #semuaorang #jangkauanluas #Gaundaurulang #busanadaurulang #karnaval #koranbekas #plastikkertas #manfaatkandaurulang
1725107973
Daur ulang sampah plastik mu sebelum mencemari lautan
1731585461
Di cari plastik pp sablon/metaliz lebar 40 cm ke atas

Foto hanya pemanis, siyap jemput ke lokasi

Langsung chat wa aja wa.me/6281226564802
1663508168
*Halo Sahabat BPMP Banten*
Plastik yang kamu buang hari ini... bisa mencemari bumi hingga ratusan tahun ke depan."
Hari ini, 5 Juni, kita peringati Hari Lingkungan Hidup Sedunia.
Tahun ini, kita diajak bersama-sama #HentikanPolusiPlastik.
Bukan hanya kampanye sesaat, tapi langkah nyata—mulai dari diri sendiri.
🚯 Ganti kantong plastik dengan tas kain.
💧Bawa botol minummu sendiri.
♻️ Daur ulang, dan kurangi konsumsi sekali pakai.
Kita punya pilihan. Kita punya kekuatan.
Untuk bumi yang lebih bersih, sehat, dan lestari
1749092994
Daur ulang sampah plastik mu sebelum mencemari lautan
1731585461
Bukan hanya plastik aja yang bisa di daur ulang , pisang pun bisa di daur ulang ya teman teman 😁🫢.
Tapi jangan takut berbahaya  daur ulang yang ini menyehatkan dan mengenyangkan🤗
#keseharianIRT
 #idemasakanseharihari
#bolupisangrumahan
#reels
#fyp
1734255648
Kostum Karnaval berupa gaun daur ulang. Terbuat dari koran, plastik. Walaupun hanya terbuat dari bahan daur ulang tetapi tidak mengurangi kecantikan orang yang memakai nya. #semuaorang #jangkauanluas #Gaundaurulang #busanadaurulang #karnaval #koranbekas #plastikkertas #manfaatkandaurulang
1725107973
Daur ulang sampah plastik di rumah tidak hanya membantu mengurangi limbah plastik yang merusak lingkungan, tetapi juga memberikan kesempatan untuk berkreasi dan membuat barang-barang berguna.
1720751613
Bukan Hanya Plastik Yang Bisa Di Daur Ulang
#photolucu #Durian #Duren #musimDurian
1737338546
Jenis kode daur ulang plastik ♻️
Belajar mengenal kode daur ulang plastik.
Simak selengkapnya hanya di Chanel GUNDUL RONGSOK ✅

Subscribe Like dan Share
GUNDUL RONGSOK channel
https://youtu.be/ThX_0El7EUw?si=89IgAar4CBCppRlQ

#recycle #daurulang #waste #pemulungnaikkelas #belajar
1748693711
Sehari 2 Sesi Kelas Daur Ulang Plastik Untuk Calon Guru
https://youtu.be/NNc99vfl_5g?si=3MqnkaMMkw1EZKG4
Saksikan hanya YouTube channel Taufiq Saguanto
1733079835
D cari PP sablon siap pelet
Untuk d daur ulang
Wa081319069108
Foto hanya pemanis.
1661319847
Daur ulang bukan hanya tentang mengurangi sampah, tapi juga menciptakan keindahan dari hal yang tak terduga. Seperti bonsai sakura dari botol plastik.
1746230508
Pengin bikin Kaligrafi 3D 😘🌸 dari Recycle daur ulang sampah plastik, kardus , dll..☘️🌿❄️💢🌸☘️untuk kegiatan pra manula 😀 foto foto itu hanya inspirasi dari google..
1706390032
Alhamdulillah walau hanya kurleb 2 jam dpt ilmu membuat hasil daur ulang plastik assoy / kresek.Terima kasih ilmu nya bu Voni & pak Alfi Fahmi.
1729318288
Maasyah Allah hasil karya daur ulang plastik😍hanya untuk lomba kreasi bukan untuk fashion show 🤭🤣🤣
1745071572
Sehari 2 Sesi Kelas Daur Ulang Plastik Untuk Calon Guru
https://youtu.be/NNc99vfl_5g?si=3MqnkaMMkw1EZKG4
Saksikan hanya YouTube channel Taufiq Saguanto
1733079835
Hanya pemula di dunia daur ulang
1727848437
Perabot Plastik Stylish dan Ramah Lingkungan? 🌿

IJM jawabannya! Dengan desain modern dan bahan daur ulang yang aman, perabot plastik dari IJM tak hanya mempercantik rumahmu, tapi juga membantu menjaga lingkungan. Kualitas terjamin, tampilannya keren, dan harganya pun tetap terjangkau!

Yuk, buat pilihan cerdas untuk rumah yang nyaman dan bumi yang lebih sehat.

IJM siap kirim perabotan impianmu langsung ke rumah hari ini! 🚛✨

Dapatkan harga spesial dengan klik link di bio sekarang!

#PerabotanRumah #PerabotanTerjangkau #PerabotanPlastik #RamahLingkungan #PlastikDaurUlang #PerabotanAman #PerabotanBerkualitas #RumahMinimalis #DekorasiRumah #InteriorRumah #RumahSehat #PilihanHemat #FurnitureRumah #PerabotRumahModern #EcoFriendly #ProdukDaurUlang #RumahNyaman #RumahTangga #SolusiRumah #PlastikAman #DesainRumah #KebutuhanRumah #RumahRamahLingkungan #FurnitureMinimalis #belanjahematyayogya
1729677853
Bukan hanya plastik yang dapat di daur ulang, ikan juga bisa di daur ulang loh 👏👏💖
Selamat makan siang semuanya..
Kali ini menu ikan sambal rujak

#makansiang #masakanseharihari #fotoviral #fyp #fbpro
1709534066
Alat daur ulang yang bisa menginspirasi kita untuk diarahkan memanfaatkan barang-barang yang tidak terpakai lagi, khususnya botol plastik. Silahkan simak video ini.

NB: hanya video cara kerja bukan bagaimana cara membuat alat 🙏🙏
1714727387
KODE DAUR ULANG

Sering kita temukan kode2 angka dengan 3 panah melingkar pada sebuah kemasan, tidak hanya plastik, tapi juga pada kemasan kertas, kaca, dan logam.

Simbol ini dirancang pada tahun 1970 oleh Gary Anderson, seorang mahasiswa di University of Southern California. Desainnya merupakan bagian dari kontes nasional yang disponsori oleh Container Corporation of America (CCA) sebagai tanggapan terhadap Hari Bumi Sedunia. Karena konsumen menjadi lebih sadar lingkungan, CCA ingin mengembangkan label untuk produk daur ulang dan dapat didaur ulang serta meningkatkan kesadaran tentang daur ulang.


In [ ]:
import pandas as pd

facebook_temp_data = FacebookAPICall("daur ulang plastik hanya", 200)

fb_df = pd.DataFrame()
fb_df["text"] = [post["message"] for post in facebook_temp_data]
fb_df["text"].apply(remove_links, inplace=True)

In [60]:
fb_df

                                                  text
0     Hanya replika bonsai daur ulang plastik kresek 🙏
1    Kembali, Ketua Umum Adupi Christine Halim diwa...
2    Hari jum'at kemarin tgl 26, hari terahir sy ju...
3          hanya Replika ( daur ulang sampah plastik )
4    Beberapa simbol daur ulang yang perlu kita ket...
..                                                 ...
110  Moorlife itu bukan untuk pajangan ya bun\nBuka...
111  🌏 Plastik Bukan Trend Lagi, Saatnya Pilih Kema...
112  Sampah sedotan plastik sebanyak ini kami kumpu...
113  🌍♻️ *Mengubah Sampah Menjadi Berkah: Daur Ulan...
114  WPC atau wood plastic composite tampak seperti...

[115 rows x 1 columns]

In [61]:
fb_df.drop_duplicates(subset=["text"], inplace=True)

In [62]:
fb_df

                                                  text
0     Hanya replika bonsai daur ulang plastik kresek 🙏
1    Kembali, Ketua Umum Adupi Christine Halim diwa...
2    Hari jum'at kemarin tgl 26, hari terahir sy ju...
3          hanya Replika ( daur ulang sampah plastik )
4    Beberapa simbol daur ulang yang perlu kita ket...
..                                                 ...
110  Moorlife itu bukan untuk pajangan ya bun\nBuka...
111  🌏 Plastik Bukan Trend Lagi, Saatnya Pilih Kema...
112  Sampah sedotan plastik sebanyak ini kami kumpu...
113  🌍♻️ *Mengubah Sampah Menjadi Berkah: Daur Ulan...
114  WPC atau wood plastic composite tampak seperti...

[83 rows x 1 columns]

In [63]:
old_data = pd.read_csv('facebook_results.csv')
old_data = old_data.drop_duplicates()
#drop duplicates from old_data in new data
fb_df = fb_df[~fb_df['text'].isin(old_data['text'])]

In [ ]:
fb_df = pd.read_csv('facebook_posts.csv')
fb_df["text"].dropna(inplace=True)
fb_df = fb_df[fb_df['text'].apply(lambda x: isinstance(x, str))]
fb_df['text'] = fb_df['text'].apply(remove_links)

fb_df.to_csv('facebook_posts.csv')

In [65]:
fb_df.to_csv('facebook_results_new.csv', index=False)

In [67]:
fb_df = pd.read_csv('facebook_results_new.csv')
fb_df_old = pd.read_csv('facebook_results.csv')
fb_df = pd.concat([fb_df, fb_df_old], ignore_index=True)
fb_df.to_csv('facebook_results.csv', index=False, header=True)
fb_df

                                                  text  Unnamed: 0
0     Hanya replika bonsai daur ulang plastik kresek 🙏         NaN
1    Kembali, Ketua Umum Adupi Christine Halim diwa...         NaN
2    Hari jum'at kemarin tgl 26, hari terahir sy ju...         NaN
3          hanya Replika ( daur ulang sampah plastik )         NaN
4    Beberapa simbol daur ulang yang perlu kita ket...         NaN
..                                                 ...         ...
329  Kreasi daur ulang sampah plastik.\r\n\r\n#art ...       216.0
330  Kreasi Daur Ulang Sampah Plastik \r\nTutorial ...       217.0
331  Hasil daur ulang sampah plastik menjadi ecobri...       218.0
332  Daur ulang sampah Plastik menjadi Kursi plasti...       219.0
333                                               text       220.0

[334 rows x 2 columns]